### ISSUE TITLE
TKT-2024-1764. JNOAUTO2 - Revision Contrato 1112 Emermedica

### ISSUE THREAD

**Issue by Mlarasspedia** [QS-StoneERP/StoneERP#106]
# Issue: Prioridad alta - Cierre Seguridad Social no trae línea de salarios 189204

## 1. Información General del Ticket

- **ID del Ticket:** TKT-2024-1764
- **Fecha de Creación:** Hoy, 07:35
- **Solicitante:** Juan Carlos Ramos - EMERMEDICA S.A.
- **Prioridad:** Alta
- **Estado Actual:** Análisis Consultoría
- **Descripción Resumida:** Agradecemos de carácter prioritario soporte con Quality, ya que al tercero solo le está trayendo la línea de vacaciones y no la de salarios. Desde nómina no podemos solucionar esta novedad.

## 2. Objetivo del Usuario

Garantizar que el cierre de Seguridad Social incluya tanto la línea de vacaciones como la de salarios, asegurando que los datos enviados al tercero sean completos y correctos.

## 3. Situación Actual y Validaciones Requeridas

- **Situación Actual:** El cierre de Seguridad Social únicamente está trayendo la línea de vacaciones, omitiendo la de salarios, lo que genera inconsistencias en los datos enviados al tercero.
- **Validaciones Requeridas:**
  - Verificar la configuración del sistema Quality para el cierre de Seguridad Social.
  - Asegurar la correcta integración entre Nómina y Quality.
  - Validar la generación completa de las líneas (vacaciones y salarios) en ambiente de pruebas antes de pasar a producción.

### Fase 1: Análisis y Planificación

1. Revisar la configuración actual de Quality para la generación de líneas.
2. Confirmar con el equipo de consultoría cualquier ajuste necesario en los parámetros.

### Fase 2: Desarrollo

1. Implement

**Comment by AlixBelthaMoreno** [comment]
Se devuelve a desarrollo porque ya sale la linea pero el valor que toma no es.

**Comment by AlixBelthaMoreno** [comment]
Se revisa el ultimo ejecutable enviado anoche y ya esta liquidando correctamente el valor. se pasa a pruebas cliente. 
El QA devolvió el formato 041, se actualiza lo que solicita y se vuelve a colocar en el tk.
