### ISSUE TITLE
tk-2024-1820 -- Actualización programas JRHFUNCI y JNORFUEN

### ISSUE THREAD

**Issue by AlixBelthaMoreno** [QS-StoneERP/StoneERP#136]
Se valida el problema y con los últimos ejecutables no suceden las incidencias que reporta el usuario.  Se pasa a pruebas cliente.

**Comment by AlixBelthaMoreno** [comment]
Se pasa a pruebas cliente para su validación.

**Comment by Mlarasspedia** [comment]
Entregado a la ing. Alix (13/0/2025  a las 6:00 pm)
