### ISSUE TITLE
Ajuste Contabilización Notas Crédito Refacturación 3010

### ISSUE THREAD

**Issue by AngelAvendan** [QS-StoneERP/StoneERP#24]
## 1. Información General del Ticket
* **Item**: Notas Crédito Refacturación 3010
* **Título**: Ajuste Contabilización Notas Crédito Refacturación 3010
* **Fecha de Creación**: 1 de septiembre de 2024
* **Solicitante**: Emermedica  
* **Tipo**: Desarrollo
* **Prioridad**: Alta

## 2. Objetivo del Usuario
* Contabilizar correctamente las notas crédito de refacturación 3010 correspondientes a facturas emitidas de periodos anteriores.
* Ajustar el proceso contable según los lineamientos de la nota 3010.

### Problemas Identificados:
1. Las notas crédito 3010 no están generando los movimientos contables adecuados cuando corresponden a facturas de años anteriores.
2. Se requiere diferenciar el tratamiento contable cuando la nota crédito es por el valor total de la factura vs un valor parcial.
3. El cambio debe aplicarse tanto para notas crédito aplicadas por plano como directamente en el módulo.

### Antecedentes:
* Se emitió la nota 3010 con lineamientos para la contabilización de notas crédito de refacturación.
* Actualmente el sistema genera un movimiento estándar que no se ajusta a lo requerido en la nota.
* Las notas crédito involucradas corresponden a facturas de periodos anteriores.

### Fase de Preparación:
* Recepción del ticket 
* Análisis inicial del consultor
* Asignación a desarrolladores Yesid Campos y Ricardo Gene
* Estimación de tiempo de desarrollo: 16 horas

### Fase de Desarrollo:
Ajuste contabilización notas crédito 3010:
* Identificar notas crédito 3010 de facturas de años anteriores
* Implementar lógica para NC de valor total según nota 3010 numeral 1.1
* Implementar lógica para NC de valor parcial según nota 3010 numeral 1.2
* Mantener generación automática de nueva factura
* Aplicar cambios para NC por plano y módulo directo

### Fase de Pruebas:
* Generar NC 3010 de factura año anterior por valor total
* Validar movimiento contable según numeral 1.1 
* Generar NC 3010 de factura año anterior por valor parcial
* Validar movimiento contable según numeral 1.2
* Verificar generación automática de nueva factura
* Probar cambios con NC aplicada por plano y módulo

## 5. Estado Actual
* **Estado**: Análisis Inicial
* **Análisis Inicial**: Asignado   
* **Desarrollador**: Yesid Campos, Ricardo Gene
* **Tiempo Estimado**: 17 horas, 
* **Tiempo ejecutado**: 12 horas

## 6. Definition of Done
- [x] Notas crédito 3010 de facturas años anteriores generan movimiento contable según nota.
- [x] Al aplicar la NC se genera automáticamente la nueva factura.
- [x] Alistamiento de Data.
- [x] Cambios aplicados para NC por plano y módulo.
- [x] Pruebas exitosas de NC de valor total y parcial con resultados contables correctos.
- [x] Validación resultado migración de  notas 3010.
- [x] Reversar data para prueba con usuario.
- [x] Documentación actualizada con la nueva lógica implementada.
- [x] Entrega validada y aprobada por el usuario solicitante.

**Comment by AngelAvendan** [comment]
Falta casos de usos terminar de chequear  
Se genera Reunión para completa la validación del entregable 3010
2:40 del día 25-11-2024
25 de Noviembre de 2024: Validación de las cuentas a las cuales corresponden los valores aplicados al generar 3010
27-11-2024: Entrega de SPs con Mergue de producción:
- Se aplazan entrega definitiva a usuario por actualización de DB y agendas de usuarios para el día Lunes 2 de Dic de 2024.

1.  pruebas de los módulos.

**Comment by yecampos** [comment]
- Stopper: 1:45 horas, 7/11/2024 (Envío facturas - Adjuntos Azure) 
- Stopper: 1:00 horas, Revisión liquidación no generada a Asesor  
Avance- Alistamiento de Data 70%
 -- Stopper: 1:00 horas, Revisión liquidación no generada a Asesor - comisiones
-- Stopper: 12-11-2024, 6 horas, comisiones y envío facturación 
Tiempo espera: 13-11-2024: Se entrega QA emermédica se espera respuesta por parte de ellos.

--  Reversar data para prueba con usuario. 50%

**Comment by nserrano123** [comment]
Yesid indica que se soluciona hoy.

**Comment by AngelAvendan** [comment]
Documentación actualizada con la nueva lógica implementada se realiza entrega del actividad of done termina hoy 21 - 11- 2024.
