### ISSUE TITLE
JNOPRPA2 - Solicitud revisión y corrección fecha en contabilización módulo de seguridad social 187324

### ISSUE THREAD

**Issue by AlixBelthaMoreno** [QS-StoneERP/StoneERP#38]
# Solicitud revisión y corrección fecha en contabilización módulo de seguridad social 187324

## 1. Información General del Ticket

* **Item**: TKT-2024-1532 coomotor
* **Item**:TKT-2024-1671 Cosechar
* **Item**:TKT-2024-1641 Emermedica
* **Item**: TKT-2024-1640 Tierra Grata

* **Fecha de Creación**: 06.11.2024
* **Solicitante**: Emermedica
* **Tipo**: Requerimiento
* **Prioridad**: Media
* **Estado**: Asignado a Desarrollo
* **Responsable**: des-mlara
* **Fecha Finalización**: 22.11.2024

[El resto del contenido continúa igual...]

## 2. Objetivo del Usuario
* Corregir la validación de fechas en la contabilización de seguridad social
* Asegurar la correcta herencia de centros de costo en cuentas por pagar
* Permitir la contabilización con el formato de fecha correcto independiente de la configuración del SQL

### Problemas Identificados:
1. Sistema no permite contabilizar con fecha 30/10/2024 debido a conflicto de formato (MM/DD/AAAA)
2. Mensaje persistente de "fecha no válida" al intentar cambiar manualmente
3. Centro de costo queda en cero en las cuentas por pagar
4. Usuario tuvo que usar fecha incorrecta (10/02/2024) para poder contabilizar

### Antecedentes:
* Cambio de configuración SQL a formato MM/DD/AAAA
* Error ocurrido durante el cierre de octubre 2024
* Problema detectado en servidor remoto de procesos
* Afecta al módulo de seguridad social

### Fase de Preparación:
* Recepción y análisis del ticket
* Validación inicial del requerimiento
* Asignación al equipo de desarrollo

### Fase de Desarrollo:
Corrección de validación de fechas:
* Implementar validación de formato de fecha independiente de configuración SQL
* Corregir herencia de centro de costo en CxP
* Validar características de cuenta para centro de costo
* Implementar manejo de diferentes formatos de fecha e idiomas

### Fase de Pruebas:
* Verificar contabilización con diferentes formatos de fecha
* Validar herencia correcta de centros de costo
* Realizar pruebas en servidor remoto
* Validación con usuario final

## 5. Estado Actual
* **Estado**: Asignado a Desarrollo
* **Análisis Inicial**: Completado
* **Desarrollador**: des-mlara
* **Tiempo Estimado**: 
  - Análisis y desarrollo: 8 días
  - Pruebas internas: 4 días
  - Pruebas cliente: 4 días
  - Total: 16 días hábiles

## 6. Definition of Done

 - [x] Recepción y análisis del ticket
 - [x] Validación inicial del requerimiento
 - [x] Asignación al equipo de desarrollo

## Fase de Desarrollo

1. Corrección de Formato de Fechas
  - [x] Validación exitosa de fechas en formato DD/MM/AAAA
  - [x] Funcionamiento correcto independiente de la configuración SQL
  - [x] Pruebas exitosas con diferentes configuraciones regionales
  - [x] Validación exitosa de fechas en formato MM/DD/AAAA

2. Corrección de Centros de Costo
  - [x] Herencia correcta del centro de costo en CxP
  - [x] Validación de características de cuenta implementada
  - [x] Centro de costo manual respetado cuando se ingresa
  - [x] Pruebas exitosas de herencia de centro de costo

3. Validaciones del Sistema
  - [ ] Mensajes de error claros y precisos implementados
  - [x] Validaciones de fecha funcionando correctamente
  - [ ] Manejo adecuado de diferentes idiomas
  - [ ] Logs de error implementados para debugging

4. Pruebas y Documentación
  - [x] Pruebas realizadas en servidor remoto
  - [ ] Documentación de cambios realizada
  - [ ] Manual de usuario actualizado
  - [ ] Pruebas exitosas de contabilización de octubre

5. Aprobación Final
  - [x] Validación del usuario en ambiente de pruebas
  - [ ] Contabilización exitosa con fecha 30/10/2024
  - [ ] Verificación de centros de costo en CxP
  - [ ] Aprobación formal del usuario

**Comment by Mlarasspedia** [comment]
Entregado al ing. Rgene; hoy : 2024-11-18 lo subí a CAS

Se valido el tema de fecha y de centro de costo,  se anexa el programa al tk de emermedica y estamos a la espera de la programación de reunión con TIC's inicialmente y posteriormente con el usuario final.

**Comment by Mlarasspedia** [comment]
- [x] Entregado el programa JNOAPPRO:
MODIFICACIONES
1.  Enlazar el campo COD_TIDI (tipo de distribución) en la tabla NO_RAPTP con la tabla NO_TIDIS 
2.  No usar LA CUENTA DEBITO Y CREDITO de esta tabla. Guardar 0 (en 

- [x] Entregado version de JNOPRPA2:

con esta modifcacion ya se solucionan estos TKT
Item: TKT-2024-1532 coomotor
Item:TKT-2024-1671 Cosechar (Solucionado: Pruebas cliente)
Item:TKT-2024-1641 Emermedica
Item: TKT-2024-1640 Tierra Grata

**Comment by AlixBelthaMoreno** [comment]
Se realizan pruebas funcionales con el usuario final de cosechar (tk-2024-1671) y se detecta que en el proceso de provisiones en el movimiento debito, ya no esta distribuyendo o colocando el punto de venta de acuerdo al centro de costo del funcionario.
Se devuelve a desarrollo para su corrección.

**Comment by AngelAvendan** [comment]
03-12-2024 compromiso por el @Mlarasspedia Fecha Fin Dec 3, 2024.

Se genera compromiso. 

09-12-2024 compromiso por el @Mlarasspedia Fecha Fin 09-12-2024 nuevo.
Se genera compromiso.

**Comment by AlixBelthaMoreno** [comment]
TKT-2024-1641 Emermedica --  Se valido con TIC, los datos y quedo programada sesión con Usuario final cuando actualicen la BD ya que el usuario solicito tener todo el ambiente en pruebas para realizarlo.  Se coordino para el 17 de diciembre 2024.
