### ISSUE TITLE
TKT-2024-1595 Modificación Reporte Planilla Cierre Proveedores JINRCIPR

### ISSUE THREAD

**Issue by Mlarasspedia** [QS-StoneERP/StoneERP#39]
# Modificación Reporte Planilla Cierre Proveedores

## 1. Información General del Ticket
* **Item**: TKT-2024-1595
* **Fecha de Creación**: 29/10/2024
* **Solicitante**: Andres Felipe Caballero
* **Tipo**: Requerimiento
* **Prioridad**: Media

## 2. Objetivo del Usuario
* Agregar información de código y nombre de bodega en el reporte de planilla para cierre de proveedor - sugerido a comprar
* Implementar modificación para empresas 10 y 11

### Problemas Identificados:
1. El reporte actual no muestra el código y nombre de la bodega junto al proveedor
2. Se requiere esta información para mejor gestión del cierre de proveedores
3. Modificación necesaria para dos empresas específicas

### Antecedentes:
* Sistema: SE - GA- Módulo Inventarios
* Producto: ERP-ENT- Stone Enterprise
* Sección: ERP | Gestión Administrativa | Inventarios
* Empresas afectadas: Empresa 10 y 11 (Agropecuaria)
* Solicitado por: Área de Contabilidad

### Fase de Preparación:
* Recepción del ticket
* Análisis inicial por consultor
* Asignación a desarrollador
* Estimación de tiempos

### Fase de Desarrollo:
Modificación del reporte:
* Análisis de la estructura actual del reporte
* Identificación de campos de bodega requeridos
* Modificación del diseño del reporte
* Implementación de nuevas columnas
* Configuración específica para empresas 10 y 11

### Fase de Pruebas:
* Validación del reporte modificado en ambiente de pruebas
* Verificación de datos de bodega
* Pruebas en empresa 10
* Pruebas en empresa 11
* Validación con usuario final

## 5. Estado Actual
* **Estado**: Asignado Desarrollo
* **Análisis Inicial**: En proceso
* **Desarrollador**: Por Definir
* **Tiempo Estimado**:
  * Análisis: 30 minutos
  * Desarrollo: 2 horas
  * Pruebas: 1 horas
  * **Total**: 3.30 horas

## 6. Definition of Done
- [x] Generado Reporte versión actual
- [x] Verificado cambios requeridos
- [x] Documentado el caso en CAS
- [x] #40
- [x] Verificada correcta visualización de información de bodega
- [x] Validado funcionamiento en Empresa 10
- [x] Validado funcionamiento en Empresa 11
- [x] Verificada integridad de datos existentes en el reporte
- [x] Realizada prueba de generación completa del reporte
- [x] Validado tiempo de respuesta del reporte modificado
- [x] Documentada la modificación realizada
- [x] Realizada capacitación a usuarios finales
- [x] Aprobación por parte del área de Contabilidad
- [x] Verificado que no hay afectación en otras empresas

¿Necesita que agregue o modifique algún aspecto específico del ticket?

**Comment by macandel** [comment]
Entregado al usuario a satisfacción
