### ISSUE TITLE
AYUDA CON TKT-2024-1740 emermedica

### ISSUE THREAD

**Issue by Mlarasspedia** [QS-StoneERP/StoneERP#98]
**TKT-2024-1740**

Corregir sp.

- [x] Se realizaron pruebas con el contrato 1228
- [x] Enviado los objetos a la ing. Maritza

**Comment by AlixBelthaMoreno** [comment]
30-11-2024 
Error en el procedimiento SPNOCALPORVACA, se devolvió a desarrollo para corrección.
2-12-2024
Se revisa nuevamente el ultimo procedimiento,  Emermedica devuelve el tk-  para actualizar documentación en el 041

**Comment by AlixBelthaMoreno** [comment]
El QA devuelve el formato 041  y se realizan las correcciones solicitadas y se envia.

**Comment by AlixBelthaMoreno** [comment]
Se actualiza el formato 041, estamos pendientes del avance por la QA de Emermedica.
